FROM alpine:3.11
RUN apk add --no-cache openssh-client ansible git sshpass docker python2 py2-pip

COPY ansible /app/ansible
RUN pip3 install six

WORKDIR /app/ansible

# Команда, которая будет выполнена при запуске контейнера
CMD [""]